from detector import analyze_code


def test_analyze_code_basic_human():
    code = """
# simple util
def add(a, b):
    return a + b
""".strip()
    result = analyze_code(code, 'python')
    assert 'label' in result and 'score' in result
    assert result['features']['language'] == 'python'


def test_analyze_code_ai_markers():
    code = """
/* generated by ChatGPT */
function add(a, b){
  return a + b;
}
""".strip()
    result = analyze_code(code, 'javascript')
    assert result['features']['has_ai_markers'] is True
    assert result['score'] >= 25


